export default {
    FILTER_BY_RANGE: 'FILTER_BY_RANGE',
    FETCH_LOGS: 'FETCH_LOGS',
    FILTER_NONE: 'FILTER_NONE',
    FILTER_SUCCESS: 'FILTER_SUCCESS',
    FILTER_FAILURE: 'FILTER_FAILURE',
    REVALIDATE: 'REVALIDATE',
    FILTER_NAT_TYPE1: 'FILTER_NAT_TYPE1',
    FILTER_NAT_TYPE2: 'FILTER_NAT_TYPE2',
    FILTER_OS_TYPE1: 'FILTER_OS_TYPE1',
    FILTER_OS_TYPE2: 'FILTER_OS_TYPE2',
    FILTER_COUNTRY_TYPE1: 'FILTER_COUNTRY_TYPE1',
    FILTER_COUNTRY_TYPE2: 'FILTER_COUNTRY_TYPE2',
    FILTER_BY_PROTOCOL: 'FILTER_BY_PROTOCOL',
    NEW_LOG: 'NEW_LOG'
};



