export default {
    FILTER_BY_RANGE: 'FILTER_BY_RANGE',
    FETCH_LOGS: 'FETCH_LOGS',
    FILTER_NONE: 'FILTER_NONE',
    FILTER_SUCCESS: 'FILTER_SUCCESS',
    FILTER_FAILURE: 'FILTER_FAILURE',
    FILTER_REQUESTER_NAT: 'FILTER_REQUESTER_NAT',
    FILTER_RESPONDER_NAT: 'FILTER_RESPONDER_NAT',
    FILTER_REQUESTER_OS: 'FILTER_REQUESTER_OS',
    FILTER_RESPONDER_OS: 'FILTER_RESPONDER_OS',
    FILTER_REQUESTER_COUNTRY: 'FILTER_REQUESTER_COUNTRY',
    FILTER_RESPONDER_COUNTRY: 'FILTER_RESPONDER_COUNTRY',
    FILTER_BY_PROTOCOL: 'FILTER_BY_PROTOCOL'
};



